//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regoin_Champ.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountant
    {
        public int Id { get; set; }
        public int LoginPasswordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime LastEnterDate { get; set; }
        public string InsuranceCompanyBills { get; set; }
    
        public virtual PasswordsLogins PasswordsLogins { get; set; }
    }
}
