//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regoin_Champ.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laborant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laborant()
        {
            this.ServiceRendered = new HashSet<ServiceRendered>();
            this.Service_lab = new HashSet<Service_lab>();
        }
    
        public int Id { get; set; }
        public int LoginPasswordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronomic { get; set; }
        public string Ip { get; set; }
        public string Lastenter { get; set; }
        public int Type { get; set; }
    
        public virtual PasswordsLogins PasswordsLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRendered> ServiceRendered { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_lab> Service_lab { get; set; }
    }
}
