//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regoin_Champ.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Labaratory_DBEntities1 : DbContext
    {
        public Labaratory_DBEntities1()
            : base("name=Labaratory_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accountant> Accountant { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Analizator> Analizator { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompany { get; set; }
        public virtual DbSet<Laborant> Laborant { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<PasswordsLogins> PasswordsLogins { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Service_lab> Service_lab { get; set; }
        public virtual DbSet<ServiceRendered> ServiceRendered { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<StatusService> StatusService { get; set; }
    }
}
