//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regoin_Champ.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> StatusOrder { get; set; }
        public Nullable<int> StatusService { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> LeadTime { get; set; }
    
        public virtual Service_lab Service_lab { get; set; }
        public virtual StatusOrder StatusOrder1 { get; set; }
        public virtual StatusService StatusService1 { get; set; }
    }
}
