//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regoin_Champ.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public int LoginPasswordId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public int PassportSerias { get; set; }
        public int PassportNumer { get; set; }
        public double Phone { get; set; }
        public string Email { get; set; }
        public double InsurancePolicyNumber { get; set; }
        public int InsuranceCompany { get; set; }
        public string ip { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany1 { get; set; }
        public virtual PasswordsLogins PasswordsLogins { get; set; }
    }
}
