//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regoin_Champ.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRendered
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int AnalizatorId { get; set; }
        public System.DateTime Date { get; set; }
        public int LaborantId { get; set; }
    
        public virtual Analizator Analizator { get; set; }
        public virtual Laborant Laborant { get; set; }
        public virtual Service_lab Service_lab { get; set; }
    }
}
